name: Package Unreal Engine Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    name: Package Unreal Engine Game
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package Project
        env: 
          UE_PATH: 'D:\Epic Games\UE_5.4' # Path to your Unreal Engine installation
          PROJECT_PATH: 'D:\External Project\Building Unreal CICD Engine (2024.11.18)\test\CICDExample\CICDExample.uproject' # Path to your Unreal project file
          OUTPUT_PATH: 'D:\External Project\Building Unreal CICD Engine (2024.11.18)\test\CICDExample' # Path to where you want to store the packaged game
        run: |
          # Try to run empty UAT to check for correct path
          & $env:UE_PATH\Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -project="$env:PROJECT_PATH" -noP4 -platform=Win64 -clientconfig=Development -serverconfig=Development -cook -allmaps -build -stage -pak -archive -archivedirectory="$env:OUTPUT_PATH"
